### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by veggiemonk**

### CODE REVIEW

**Comment by Andrey9kin** [comment]
I assume you know what you are doing and not picking a license randomly. In other words, I trust your choice

**Review by Andrey9kin — APPROVED** [review]

**Comment by veggiemonk** [comment]
I was hesitating between Apache and Mozilla license.... I thought you might know something about it.
I don't know how this apply for the audio media so it needs more digging.

Let's close that for the moment and think about it before jumping into it.

**Comment by Andrey9kin** [comment]
@veggiemonk checked a couple of other podcasts and it seems that Creative Commons should be a thing. But reference to that should be on the web site https://creativecommons.org/licenses/by-nc-nd/3.0/ not in the repo

**Comment by Andrey9kin** [comment]
Here is an example https://twit.tv/about/license

**Comment by veggiemonk** [comment]
I researched a bit and the https://creativecommons.org/licenses/by-nc-nd/3.0/ license is the best as it seems

**Pull request closed without merging**
